name: Deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
  
      - name: Install WebAssembly tools
        run: dotnet workload install wasm-tools
  
      - name: Build the project
        run: dotnet publish ZeldaMusicRandomizer.Browser -c Release -o build
        
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/wwwroot/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4